 - name: Commit and Push Changes
 env:
    PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  run: |
    git config --local user.email "github-actions[bot]@users.noreply.github.com"
    git config --local user.name "GitHub Actions"
    git add README.md
    git commit -m "Atualizando dados do README" || echo "Nada a commitar, README não foi alterado."
    git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
